[tool.ruff]
line-length = 150
target-version = "py312"
lint.select = ["ALL"]
lint.ignore = [
    "N803", # Argument should be lowercase
    "T201", # Print found
]

[tool.mypy]
disallow_untyped_defs = true
python_version = "3.12"
ignore_missing_imports = true
strict = true

[tool.nbqa.mypy]
addopts = ["--ignore-missing-imports"]

[tool.nbqa.exclude]
notebooks = ["*/.ipynb_checkpoints/*"]

