[tool.ruff]
line-length = 100
target-version = "py312"
lint.select = ["ALL"]

[tool.mypy]
disallow_untyped_defs = true
python_version = "3.12"
ignore_missing_imports = true
strict = true

[tool.nbqa.mypy]
addopts = ["--ignore-missing-imports"]

[tool.nbqa.exclude]
notebooks = ["*/.ipynb_checkpoints/*"]
